// <auto-generated />
using System;
using Infra.Ef.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Ef.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230423005317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infra.Ef.DataModel.TbActive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("act_id");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("act_category");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cpy_id");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("act_price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("act_ticker");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tb_actives", t =>
                        {
                            t.HasComment("sufix: act");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("078602da-0a77-42f0-a6bc-1a2db3be6cf1"),
                            Category = 0,
                            CompanyId = new Guid("5de9bdc7-2701-4485-97b0-e0844c86ea68"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1136),
                            Enabled = (byte)1,
                            Price = 10.8m,
                            Ticker = "MGLU3",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        },
                        new
                        {
                            Id = new Guid("cc22ceb3-cf16-4e08-aafc-d732b8f42317"),
                            Category = 0,
                            CompanyId = new Guid("04996bb3-502b-41ae-9972-afe76a69f6a2"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1142),
                            Enabled = (byte)1,
                            Price = 40.7m,
                            Ticker = "BBAS3",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbActivesOfCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("aoc_id");

                    b.Property<Guid?>("ActiveId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("act_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("aoc_amount");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bkr_id");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("datetime2")
                        .HasColumnName("aoc_date_operation");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<int>("Operation")
                        .HasColumnType("int")
                        .HasColumnName("aoc_operation");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("aoc_unit_cost");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usu_id");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wal_Id");

                    b.HasKey("Id");

                    b.HasIndex("ActiveId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("tb_actives_company", t =>
                        {
                            t.HasComment("sufix: aoc");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00ebd4c8-ca91-4858-9b9d-84d524feafe9"),
                            ActiveId = new Guid("078602da-0a77-42f0-a6bc-1a2db3be6cf1"),
                            Amount = 50m,
                            BrokerId = new Guid("1a7e5b4e-15b2-4a03-81d4-1f45619d5d1a"),
                            DateOperation = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1157),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1158),
                            Enabled = (byte)1,
                            Operation = 1,
                            UnitCost = 22.5m,
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            UserId = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            WalletId = new Guid("89856041-3911-44aa-bffd-3a28a4af5464")
                        },
                        new
                        {
                            Id = new Guid("7d3b139b-3022-4ea0-b3af-fd5b744f6e35"),
                            ActiveId = new Guid("cc22ceb3-cf16-4e08-aafc-d732b8f42317"),
                            Amount = 200m,
                            BrokerId = new Guid("1a7e5b4e-15b2-4a03-81d4-1f45619d5d1a"),
                            DateOperation = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1164),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1164),
                            Enabled = (byte)1,
                            Operation = 1,
                            UnitCost = 43.5m,
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            UserId = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            WalletId = new Guid("89856041-3911-44aa-bffd-3a28a4af5464")
                        },
                        new
                        {
                            Id = new Guid("6f1fb3f9-3a95-4a94-b047-5101cb3b12fa"),
                            ActiveId = new Guid("cc22ceb3-cf16-4e08-aafc-d732b8f42317"),
                            Amount = 200.121m,
                            BrokerId = new Guid("1a7e5b4e-15b2-4a03-81d4-1f45619d5d1a"),
                            DateOperation = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1167),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1167),
                            Enabled = (byte)1,
                            Operation = 1,
                            UnitCost = 43.5m,
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            UserId = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            WalletId = new Guid("89856041-3911-44aa-bffd-3a28a4af5464")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbBroker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bkr_id");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("bkr_cnpj");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bkr_corporate_name");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<string>("FantasyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("bkr_fantasy_name");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.ToTable("tb_broker", t =>
                        {
                            t.HasComment("sufix: bkr");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a7e5b4e-15b2-4a03-81d4-1f45619d5d1a"),
                            CNPJ = "48.537.525/0001-01",
                            CorporateName = "Itau",
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1070),
                            Enabled = (byte)1,
                            FantasyName = "Itau investimentos",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cpy_id");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasColumnName("cpy_cnpj");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("cpy_name");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sct_id");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("tb_company", t =>
                        {
                            t.HasComment("sufix: cpy");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5de9bdc7-2701-4485-97b0-e0844c86ea68"),
                            CNPJ = "48.537.555/0001-01",
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1121),
                            Enabled = (byte)1,
                            Name = "Magazine Luiza",
                            SetorId = new Guid("aeadc5b3-b681-4292-843e-84a0406163d4"),
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        },
                        new
                        {
                            Id = new Guid("04996bb3-502b-41ae-9972-afe76a69f6a2"),
                            CNPJ = "48.537.523/0001-01",
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1124),
                            Enabled = (byte)1,
                            Name = "Banco do Brasil",
                            SetorId = new Guid("af835580-fe43-48b3-ac7d-c601e2a61c70"),
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sct_id");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("sct_name");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.ToTable("tb_sector", t =>
                        {
                            t.HasComment("sufix: sct");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aeadc5b3-b681-4292-843e-84a0406163d4"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1048),
                            Enabled = (byte)1,
                            Name = "Varejo",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        },
                        new
                        {
                            Id = new Guid("af835580-fe43-48b3-ac7d-c601e2a61c70"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1050),
                            Enabled = (byte)1,
                            Name = "Financeiro",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usu_id");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("usu_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("usu_password");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.ToTable("tb_user", t =>
                        {
                            t.HasComment("sufix: usu");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(754),
                            Enabled = (byte)1,
                            Login = "elton",
                            Password = "123456",
                            UserCreated = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("wal_Id");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bkr_id");

                    b.Property<DateTime>("Dcreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("d_created");

                    b.Property<byte>("Enabled")
                        .HasColumnType("tinyint")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("wal_name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usu_id");

                    b.Property<Guid>("UserCreated")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_created");

                    b.Property<Guid?>("UserLastUpdate")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_last_update");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("tb_wallet", t =>
                        {
                            t.HasComment("sufix: wal");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("89856041-3911-44aa-bffd-3a28a4af5464"),
                            BrokerId = new Guid("1a7e5b4e-15b2-4a03-81d4-1f45619d5d1a"),
                            Dcreated = new DateTime(2023, 4, 22, 21, 53, 16, 940, DateTimeKind.Local).AddTicks(1085),
                            Enabled = (byte)1,
                            Name = "Minha Carteira",
                            OwnerId = new Guid("0b266425-061d-4705-a3b7-f77a2892e85a"),
                            UserCreated = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbActive", b =>
                {
                    b.HasOne("Infra.Ef.DataModel.TbCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbActivesOfCompany", b =>
                {
                    b.HasOne("Infra.Ef.DataModel.TbActive", "Active")
                        .WithMany()
                        .HasForeignKey("ActiveId");

                    b.HasOne("Infra.Ef.DataModel.TbBroker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId");

                    b.HasOne("Infra.Ef.DataModel.TbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Infra.Ef.DataModel.TbWallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Active");

                    b.Navigation("Broker");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbCompany", b =>
                {
                    b.HasOne("Infra.Ef.DataModel.TbSector", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Infra.Ef.DataModel.TbWallet", b =>
                {
                    b.HasOne("Infra.Ef.DataModel.TbBroker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId");

                    b.HasOne("Infra.Ef.DataModel.TbUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Broker");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
