// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infra.Repository.Context;
using Infra.Repository.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Infra.Repository.Context.Configurations
{
    public partial class TbSectorConfiguration : IEntityTypeConfiguration<TbSector>
    {
        public void Configure(EntityTypeBuilder<TbSector> entity)
        {
            entity.HasKey(e => e.SctId).HasName("sct_id");

            entity.ToTable("tb_sector", tb => tb.HasComment("abbreviation: sct\r\nDescription: table sector"));

            entity.Property(e => e.SctId)
            .ValueGeneratedNever()
            .HasComment("pk table");
            entity.Property(e => e.SctName).HasComment("sector name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbSector> entity);
    }
}
