// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infra.Repository.Context;
using Infra.Repository.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Infra.Repository.Context.Configurations
{
    public partial class TbWalletConfiguration : IEntityTypeConfiguration<TbWallet>
    {
        public void Configure(EntityTypeBuilder<TbWallet> entity)
        {
            entity.HasKey(e => e.WalId).HasName("wal_Id");

            entity.ToTable("tb_wallet", tb => tb.HasComment("abbreviation:  wal\r\nDescription: tables wallet"));

            entity.Property(e => e.WalId)
            .ValueGeneratedNever()
            .HasComment("PK table");
            entity.Property(e => e.WalName).HasComment("Name wallet");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbWallet> entity);
    }
}
