name: Deploy para Windows Server com IIS

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest  # O GitHub Actions rodará em um ambiente Linux

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2️⃣ Compilar o projeto (se for .NET)
      - name: Compilar aplicação .NET
        run: dotnet publish "./src/1 - Presentation/Presentation.Api/Presentation.Api.csproj" -c Release -o ./publish /p:UseAppHost=false

      # 3️⃣ Enviar arquivos via SSH para Windows Server
      - name: Copiar arquivos para o Windows Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          script: |
            New-Item -Path "C:\inetpub\wwwroot\backup" -ItemType Directory -Force
            Copy-Item -Path "C:\inetpub\wwwroot\minhaapp\*" -Destination "C:\inetpub\wwwroot\backup\$(Get-Date -Format yyyyMMdd_HHmmss)" -Recurse -Force
            Remove-Item -Path "C:\inetpub\wwwroot\minhaapp\*" -Recurse -Force
            New-Item -Path "C:\inetpub\wwwroot\minhaapp" -ItemType Directory -Force

      # 4️⃣ Transferir arquivos do GitHub para o servidor via SSH
      - name: Transferir arquivos para IIS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          source: "./publish/*"
          target: "C:/inetpub/wwwroot/minhaapp"

      # 5️⃣ Reiniciar o IIS para aplicar mudanças
      - name: Reiniciar IIS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          script: |
            iisreset
