name: Deploy para Windows Server com IIS

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest  # O GitHub Actions rodará em um ambiente Linux

    steps:
      # 1️⃣ Faz checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico seja baixado

      # 2️⃣ Listar arquivos do repositório para depuração
      - name: Listar arquivos do repositório
        run: ls -R

      # 3️⃣ Criar diretório de publicação
      - name: Criar diretório de publicação
        run: mkdir -p ./publish

      # 4️⃣ Compilar a aplicação .NET no diretório correto
      - name: Compilar aplicação .NET
        working-directory: "./src/1 - Presentation/Presentation.Api"
        run: |
          dotnet restore
          dotnet publish Presentation.Api.csproj -c Release -o ../../publish /p:UseAppHost=false

      # 5️⃣ Listar arquivos publicados para depuração
      - name: Listar arquivos publicados
        run: ls -l ./publish

      # 6️⃣ Criar backup e limpar pasta do IIS antes da cópia
      - name: Criar backup e limpar pasta do IIS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          script: |
            $backupPath = "C:\inetpub\wwwroot\backup\$(Get-Date -Format yyyyMMdd_HHmmss)"
            New-Item -Path $backupPath -ItemType Directory -Force
            if (Test-Path "C:\inetpub\wwwroot\minhaapp") {
              Copy-Item -Path "C:\inetpub\wwwroot\minhaapp\*" -Destination $backupPath -Recurse -Force
              Remove-Item -Path "C:\inetpub\wwwroot\minhaapp\*" -Recurse -Force
            }
            New-Item -Path "C:\inetpub\wwwroot\minhaapp" -ItemType Directory -Force

      # 7️⃣ Transferir arquivos publicados para o servidor Windows
      - name: Transferir arquivos para IIS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          source: "./publish/*"
          target: "C:/inetpub/wwwroot/minhaapp"

      # 8️⃣ Reiniciar IIS para aplicar mudanças
      - name: Reiniciar IIS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WIN_HOST }}
          username: ${{ secrets.WIN_USER }}
          password: ${{ secrets.WIN_PASS }}
          script: |
            iisreset
